# 网站基本信息
title: "科研分享会记录"
description: "Seminar Records of Our Group"
baseurl: "/seminar" # 替换为你的项目名
url: "https://tulipdkw.github.io" # 替换为你的用户名

# Jekyll设置
markdown: kramdown
highlighter: rouge

# SCSS/Sass配置 - 关键配置
sass:
  style: compressed           # 压缩CSS输出
  sass_dir: _sass            # 指定SCSS partial文件目录
  load_paths:                # 额外的加载路径（可选）
    - _sass

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules/           # 如果使用npm

# 默认设置
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"