# 网站基本信息
title: "科研小组分享记录"
description: "记录我们小组的学术分享与交流"
baseurl: "/projectname" # 替换为你的项目名
url: "https://username.github.io" # 替换为你的用户名

# Jekyll设置
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
  sass_dir: _sass

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# 默认设置
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"