# 网站基本信息
title: "科研小组分享记录"
subtitle: "记录学术交流与论文分享"
description: "记录我们的学术交流与论文分享，推动科研创新与合作"
baseurl: "/[projectname]"
url: "https://[username].github.io"

# Jekyll设置
markdown: kramdown
highlighter: rouge
permalink: pretty

# 构建设置
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 网站设置
author:
  name: "科研小组"
  email: "your-email@example.com"

# 社交链接
social:
  github: "your-username"
  email: "your-email@example.com"

# 集合设置
collections:
  presentations:
    output: true
    permalink: /:collection/:name/